### ISSUE TITLE
关于 do_register 返回值的问题

### ISSUE THREAD

**Issue by Haceau-Zoac** [parallel101/hw05#6]
为什么 `do_register` 函数返回值类型是 bool，但却返回了 char const *，这样不是永远返回 true 了吗

**Comment by archibate** [comment]
感谢提醒！已修复为返回string











无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月11日(周二) 下午3:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [parallel101/hw05] 关于 do_register 返回值的问题 (Issue #6)




 
为什么 do_register 函数返回值类型是 bool，但却返回了 char const *，这样不是永远返回 true 了吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
